# Generated by Django 2.0 on 2020-08-16 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.CharField(max_length=200, verbose_name='概要')),
                ('street_view', models.URLField(blank=True, null=True, verbose_name='ストリートビューURL')),
                ('country', models.CharField(max_length=200, verbose_name='国')),
                ('prefectures', models.CharField(max_length=200, verbose_name='都道府県')),
                ('city', models.CharField(max_length=200, verbose_name='市区町村')),
                ('address1', models.CharField(blank=True, max_length=200, null=True, verbose_name='丁、番地、号')),
                ('address2', models.CharField(blank=True, max_length=200, null=True, verbose_name='マンション、アパート等')),
                ('max_acceptable_users', models.IntegerField(verbose_name='最大受入可能人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='オーナー')),
            ],
            options={
                'verbose_name_plural': 'ホスト',
            },
        ),
        migrations.CreateModel(
            name='Host_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.Host', verbose_name='ホスト外部キー')),
            ],
            options={
                'verbose_name_plural': 'ホスト画像',
            },
        ),
    ]
