# Generated by Django 2.0 on 2020-08-16 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='開始日時')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了日時')),
                ('value', models.IntegerField(verbose_name='価格')),
                ('discount_value', models.IntegerField(blank=True, null=True, verbose_name='割引価格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.Host', verbose_name='ホスト外部キー')),
            ],
            options={
                'verbose_name_plural': 'ホスト料金',
            },
        ),
        migrations.CreateModel(
            name='Host_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.Host', verbose_name='ホスト外部キー')),
            ],
            options={
                'verbose_name_plural': 'ホストタグ',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(verbose_name='種別')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('detail', models.CharField(max_length=200, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'お知らせ',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stutas', models.IntegerField(verbose_name='状態区分')),
                ('start_date', models.DateField(verbose_name='開始日時')),
                ('end_date', models.DateField(verbose_name='終了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ゲスト外部キー')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.Host', verbose_name='ホスト外部キー')),
            ],
            options={
                'verbose_name_plural': '予約',
            },
        ),
        migrations.CreateModel(
            name='Reservation_Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(verbose_name='タイプ')),
                ('value', models.IntegerField(verbose_name='価格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.Reservation', verbose_name='予約外部キー')),
            ],
            options={
                'verbose_name_plural': '予約費用',
            },
        ),
        migrations.CreateModel(
            name='Reservation_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('detail', models.CharField(max_length=200, verbose_name='内容')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='匿名フラグ')),
                ('rank', models.IntegerField(verbose_name='レビューランク')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.Reservation', verbose_name='予約外部キー')),
            ],
            options={
                'verbose_name_plural': '予約レビュー',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(verbose_name='種別')),
                ('name', models.CharField(max_length=200, verbose_name='名前')),
                ('color', models.CharField(max_length=200, verbose_name='色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'タグマスター',
            },
        ),
        migrations.AddField(
            model_name='host_tag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.Tag', verbose_name='タグ外部キー'),
        ),
    ]
