# Generated by Django 2.0 on 2020-08-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'アプリモデル'},
        ),
    ]
