# Generated by Django 2.0 on 2020-08-11 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0003_auto_20200811_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name_plural': 'ホスト'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'タグマスター'},
        ),
        migrations.AlterField(
            model_name='host',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='オーナー'),
        ),
    ]
