# Generated by Django 2.0 on 2020-08-11 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0007_auto_20200811_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='host_image',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.Host', verbose_name='ホスト外部キー'),
        ),
        migrations.AlterField(
            model_name='host_image',
            name='title',
            field=models.CharField(max_length=200, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='host_image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='host_image',
            name='url',
            field=models.CharField(max_length=200, verbose_name='URL'),
        ),
    ]
