# Generated by Django 2.0 on 2020-08-11 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0008_auto_20200811_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host_Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200, verbose_name='国')),
                ('city', models.CharField(max_length=200, verbose_name='市町村')),
                ('address1', models.CharField(max_length=200, verbose_name='丁、番地、号')),
                ('address2', models.CharField(max_length=200, verbose_name='マンション、アパート等')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.Host', verbose_name='ホスト外部キー')),
            ],
            options={
                'verbose_name_plural': 'ホスト場所',
            },
        ),
    ]
