# Generated by Django 2.0 on 2020-08-11 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0009_host_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='開始日時')),
                ('end_date', models.DateField(verbose_name='終了日時')),
                ('value', models.IntegerField(verbose_name='価格')),
                ('discount_value', models.IntegerField(null=True, verbose_name='割引価格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.Host', verbose_name='ホスト外部キー')),
            ],
            options={
                'verbose_name_plural': 'ホスト料金',
            },
        ),
    ]
