# Generated by Django 2.0 on 2020-08-11 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camp', '0010_host_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'ホストタグ',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='開始日時')),
                ('end_date', models.DateField(verbose_name='終了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ゲスト外部キー')),
            ],
            options={
                'verbose_name_plural': '予約マスター',
            },
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name_plural': 'ホストマスター'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.Host', verbose_name='ホスト外部キー'),
        ),
        migrations.AddField(
            model_name='host_tag',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.Host', verbose_name='ホスト外部キー'),
        ),
        migrations.AddField(
            model_name='host_tag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.Tag', verbose_name='タグ外部キー'),
        ),
    ]
