# Generated by Django 2.0 on 2020-08-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0011_auto_20200811_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name_plural': 'ホスト'},
        ),
    ]
