# Generated by Django 2.0 on 2020-08-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0014_reservation_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='description',
            field=models.CharField(max_length=200, verbose_name='概要'),
        ),
    ]
