# Generated by Django 2.0 on 2020-08-11 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0015_auto_20200811_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='host_place',
            name='prefectures',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='都道府県'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host_place',
            name='city',
            field=models.CharField(max_length=200, verbose_name='市区町村'),
        ),
    ]
