# Generated by Django 2.0 on 2020-08-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0019_auto_20200811_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_price',
            name='discount_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='割引価格'),
        ),
    ]
