# Generated by Django 2.0 on 2020-08-13 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0020_auto_20200811_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='stutas',
            field=models.IntegerField(verbose_name='状態区分'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host',
            name='street_view',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ストリートビューURL'),
        ),
    ]
