# Generated by Django 2.0 on 2020-08-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0021_auto_20200814_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_price',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='終了日時'),
        ),
    ]
