# Generated by Django 2.0 on 2020-08-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0023_auto_20200816_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host_place',
            name='host',
        ),
        migrations.DeleteModel(
            name='Host_Place',
        ),
    ]
