# Generated by Django 2.0 on 2020-08-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200619_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ニックネーム'),
        ),
    ]
