# Generated by Django 2.0 on 2020-08-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='image_cover',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='カバー画像'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='image_user',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ユーザー画像'),
        ),
    ]
