# Generated by Django 2.0 on 2020-08-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200816_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='自己紹介'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='image_cover',
            field=models.URLField(blank=True, null=True, verbose_name='カバー画像'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='image_user',
            field=models.URLField(blank=True, null=True, verbose_name='ユーザー画像'),
        ),
    ]
